// apps/angular-app/src/app/calculator/period-calculator.component.ts
import { Component, ElementRef, EventEmitter, Input, OnChanges, OnDestroy, Output, SimpleChanges, ViewChild } from '@angular/core';
import flatpickr from 'flatpickr';
import { getFormattedStringFromDays, Period } from '@time-calculator/common';
import type { Instance } from 'flatpickr/dist/types/instance';

@Component({
  selector: 'app-period-calculator',
  standalone: true,
  host: {
    class: 'contents',
  },
  templateUrl: './period-calculator.component.html',
})
export class PeriodCalculatorComponent implements OnChanges, OnDestroy {
  @Input({ required: true }) periodInfo!: Period;
  @Output() updatePeriod = new EventEmitter<Period>();
  @Output() deletePeriod = new EventEmitter<void>();

  @ViewChild('periodPicker', { static: true }) periodPicker!: ElementRef<HTMLInputElement>;

  private picker?: Instance;

  ngOnChanges(changes: SimpleChanges): void {
    if ('periodInfo' in changes) {
      queueMicrotask(() => this.syncPicker());
    }
  }

  ngOnDestroy(): void {
    this.picker?.destroy();
  }

  formattedDays(days: number): string {
    return getFormattedStringFromDays(days);
  }

  private syncPicker(): void {
    const input = this.periodPicker?.nativeElement;
    if (!input || !this.periodInfo) {
      return;
    }

    const defaultDate = [this.periodInfo.startDate, this.periodInfo.endDate].filter(
      (date): date is Date => date !== null,
    );

    if (!this.picker) {
      this.picker = flatpickr(input, {
        mode: 'range',
        maxDate: new Date(),
        dateFormat: 'Y-m-d',
        defaultDate,
        onChange: (dates) => {
          if (dates.length === 2) {
            this.updatePeriod.emit(
              new Period({
                id: this.periodInfo.id,
                startDate: dates[0],
                endDate: dates[1],
              }),
            );
          }
        },
      }) as Instance;
      return;
    }

    this.picker.setDate(defaultDate, false);
  }
}

<div class="card bg-base-100 card-bordered shadow-xl w-full sm:w-1/2 md:w-1/3 p-2 flex flex-col gap-4">
  <div>Period</div>

  <input
    #periodPicker
    class="input input-bordered w-full"
    placeholder="Select date range"
    readonly
  />

  <div>Your time here has been {{ formattedDays(periodInfo.days) }}</div>

  <button class="btn btn-error" (click)="deletePeriod.emit()">Remove Period</button>
</div>

// apps/svelte-app/src/routes/timeCalculator/calculator/PeriodCalculator.svelte
<script lang="ts">
	import { onMount, onDestroy } from 'svelte';
	import flatpickr from 'flatpickr';
	import type { Instance } from 'flatpickr/dist/types/instance';
	import { getFormattedStringFromDays, Period } from '@time-calculator/common';

	export let period: Period;
	export let index: number;
	export let updatePeriod: (index: number, updatedPeriod: Period) => void;
	export let deletePeriod: (index: number) => void;

	let inputEl: HTMLInputElement;
	let fp: Instance;

	onMount(() => {
		const defaultDate = [period.startDate, period.endDate].filter(
			(d): d is Date => d != null
		);

		fp = flatpickr(inputEl, {
			mode: 'range',
			maxDate: new Date(),
			dateFormat: 'Y-m-d',
			defaultDate,
			onChange(dates) {
				if (dates.length === 2) {
					const updatedPeriod = new Period({
						id: period.id,
						startDate: dates[0],
						endDate: dates[1]
					});
					updatePeriod(index, updatedPeriod);
				}
			}
		}) as Instance;
	});

	onDestroy(() => {
		fp?.destroy();
	});
</script>

<div class="card bg-base-100 card-bordered shadow-xl w-full sm:w-1/2 md:w-1/3 p-2 flex flex-col gap-4">
	<div>Period</div>

	<input
		bind:this={inputEl}
		class="input input-bordered w-full"
		placeholder="Select date range"
		readonly
	/>

	<div>Your time here has been {getFormattedStringFromDays(period.days)}</div>

	<button class="btn btn-error" on:click={() => deletePeriod(index)}>
		Remove Period
	</button>
</div>
