// apps/svelte-app/src/routes/timeCalculator/MainLayout.svelte
<script lang="ts">
    import Calculator from './calculator/Calculator.svelte';
    import { getFormattedStringFromDays } from '@time-calculator/common';
  
    let totalDays = 0;
  
    const updateDays = (days: number) => {
      totalDays = days;
    };
  </script>
  
  <div class="flex justify-center flex-col items-center gap-4 p-2">
    <h1>Time Calculator</h1>
    <h2>Your time here has been {getFormattedStringFromDays(totalDays)}</h2>
    <Calculator {updateDays} />
  </div>

// apps/angular-app/src/app/main-layout.component.ts
import { Component } from '@angular/core';
import { getFormattedStringFromDays } from '@time-calculator/common';
import { CalculatorComponent } from './calculator/calculator.component';

@Component({
  selector: 'app-main-layout',
  standalone: true,
  imports: [CalculatorComponent],
  host: {
    class: 'contents',
  },
  templateUrl: './main-layout.component.html',
})
export class MainLayoutComponent {
  totalDays = 0;

  onTotalDaysChange(days: number): void {
    this.totalDays = days;
  }

  formattedDays(days: number): string {
    return getFormattedStringFromDays(days);
  }
}

<div class="flex justify-center flex-col items-center gap-4 p-2">
  <h1>Time Calculator</h1>
  <h2>Your time here has been {{ formattedDays(totalDays) }}</h2>
  <app-calculator (totalDaysChange)="onTotalDaysChange($event)"></app-calculator>
</div>
