// apps/svelte-app/src/routes/timeCalculator/calculator/Calculator.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { v4 as uuidv4 } from 'uuid';
  import PeriodCalculator from './PeriodCalculator.svelte';
  import { Period, totalDaysFromPeriodList } from '@time-calculator/common';

  // Props
  export let updateDays: (days: number) => void;

  // Reactive list of periods
  let periodList: Period[] = [];

  // Load periods from localStorage on mount
  onMount(() => {
    const periodListFromLocalStorage = JSON.parse(localStorage.getItem('periodList') || '[]');
    if (periodListFromLocalStorage.length > 0) {
      periodList = periodListFromLocalStorage.map(
        (period: { startDate: string; endDate: string; id?: string }) =>
          new Period({
            id: period.id || uuidv4(),
            startDate: new Date(period.startDate),
            endDate: new Date(period.endDate),
          })
      );
    }
  });

  // Update total days and save periods to localStorage when `periodList` changes
  $: {
    if (periodList.length > 0) {
      updateDays(totalDaysFromPeriodList(periodList));
      localStorage.setItem(
        'periodList',
        JSON.stringify(
          periodList.filter(
            (period) => period.startDate !== null && period.endDate !== null
          )
        )
      );
    }
  }

  // Add a new period
  function addPeriod() {
    periodList = [
      ...periodList,
      new Period({
        id: uuidv4(),
        startDate: null,
        endDate: null,
      }),
    ];
  }

  // Update a specific period
  function updatePeriod(index: number, updatedPeriod: Period) {
    const copyList = [...periodList];
    copyList[index] = updatedPeriod;
    periodList = copyList;
  }

  // Delete a specific period
  function deletePeriod(index: number) {
    periodList = [
      ...periodList.slice(0, index),
      ...periodList.slice(index + 1),
    ];
  }
</script>

<button class="btn" on:click={addPeriod}>Add Period</button>
<div class="flex flex-wrap justify-center w-full gap-4">
  {#each periodList as period, index}
    <PeriodCalculator
      {period}
      {index}
      {updatePeriod}
      {deletePeriod}
    />
  {/each}
</div>

// src/timeCalculator/calculator/Calculator.tsx
import { useEffect, useState } from "react";
import { v4 as uuidv4 } from 'uuid';
import PeriodCalculator from "./PeriodCalculator";
import { Period } from "./Period";
import { totalDaysFromPeriodList } from "../util/utils";

function Calculator({ updateDays }: { updateDays: (days: number) => void; }) {
    const [periodList, setPeriodList] = useState([] as Period[]);

    useEffect(() => {
        // Load Periods from Local Storage if they exist.
        const periodListFromLocalStorage = JSON.parse(localStorage.getItem('periodList') ?? '[]');
        if (periodListFromLocalStorage.length > 0 && periodList.length === 0) {
            setPeriodList(periodListFromLocalStorage.map((period:any) => new Period({ ...period,startDate: new Date(period.startDate), endDate: new Date(period.endDate) })));
        }
    }, [periodList.length]);

    useEffect(() => {
        updateDays(totalDaysFromPeriodList(periodList));
        localStorage.setItem('periodList', JSON.stringify(periodList.filter((period) => period.startDate !== null && period.endDate !== null)));
    }, [periodList, updateDays]);
    
    return (
        <>
            <button className="btn"
            onClick={() => {
                setPeriodList([...periodList, new Period({
                    id: uuidv4(),
                    startDate: null,
                    endDate: null
                })]);
            }} >Add Period</button>
            <div className="flex flex-wrap justify-center w-full gap-4">
                {
                    periodList.map((period, index) =>
                        <PeriodCalculator key={index}
                            periodInfo={period} updatePeriod={(updatePeriodValue: Period) => {
                                let copyList = [...periodList];
                                copyList[index] = updatePeriodValue;
                                setPeriodList(copyList)
                            }}
                            deletePeriod={() => {
                                setPeriodList([...periodList.slice(0, index), ...periodList.slice(index + 1)])
                            }} />)
                }
            </div>
        </>
    );
}

export default Calculator;
