// apps/react-app/src/timeCalculator/calculator/Calculator.tsx
import { useEffect, useState } from "react";
import { v4 as uuidv4 } from 'uuid';
import PeriodCalculator from "./PeriodCalculator";
import { Period } from "@time-calculator/common";
import { totalDaysFromPeriodList } from "@time-calculator/common";

function Calculator({ updateDays }: { updateDays: (days: number) => void; }) {
    const [periodList, setPeriodList] = useState([] as Period[]);

    useEffect(() => {
        // Load Periods from Local Storage if they exist.
        const periodListFromLocalStorage = JSON.parse(localStorage.getItem('periodList') ?? '[]');
        if (periodListFromLocalStorage.length > 0 && periodList.length === 0) {
            setPeriodList(periodListFromLocalStorage.map((period:any) => new Period({ ...period,startDate: new Date(period.startDate), endDate: new Date(period.endDate) })));
        }
    }, [periodList.length]);

    useEffect(() => {
        updateDays(totalDaysFromPeriodList(periodList));
        localStorage.setItem('periodList', JSON.stringify(periodList.filter((period) => period.startDate !== null && period.endDate !== null)));
    }, [periodList, updateDays]);
    
    return (
        <>
            <button className="btn"
            onClick={() => {
                setPeriodList([...periodList, new Period({
                    id: uuidv4(),
                    startDate: null,
                    endDate: null
                })]);
            }} >Add Period</button>
            <div className="flex flex-wrap justify-center w-full gap-4">
                {
                    periodList.map((period, index) =>
                        <PeriodCalculator key={index}
                            periodInfo={period} updatePeriod={(updatePeriodValue: Period) => {
                                let copyList = [...periodList];
                                copyList[index] = updatePeriodValue;
                                setPeriodList(copyList)
                            }}
                            deletePeriod={() => {
                                setPeriodList([...periodList.slice(0, index), ...periodList.slice(index + 1)])
                            }} />)
                }
            </div>
        </>
    );
}

export default Calculator;

// apps/angular-app/src/app/calculator/calculator.component.ts
import { CommonModule } from '@angular/common';
import { Component, EventEmitter, OnInit, Output } from '@angular/core';
import { Period, totalDaysFromPeriodList } from '@time-calculator/common';
import { v4 as uuidv4 } from 'uuid';
import { PeriodCalculatorComponent } from './period-calculator.component';

@Component({
  selector: 'app-calculator',
  standalone: true,
  imports: [CommonModule, PeriodCalculatorComponent],
  host: {
    class: 'contents',
  },
  templateUrl: './calculator.component.html',
})
export class CalculatorComponent implements OnInit {
  @Output() totalDaysChange = new EventEmitter<number>();

  periodList: Period[] = [];

  ngOnInit(): void {
    const storedPeriods = JSON.parse(localStorage.getItem('periodList') ?? '[]');

    this.periodList = storedPeriods.map(
      (period: { id: string; startDate: string; endDate: string }) =>
        new Period({
          id: period.id,
          startDate: new Date(period.startDate),
          endDate: new Date(period.endDate),
        }),
    );

    this.recalculateAndSave();
  }

  addPeriod(): void {
    this.periodList = [
      ...this.periodList,
      new Period({ id: uuidv4(), startDate: null, endDate: null }),
    ];
    this.recalculateAndSave();
  }

  onUpdatePeriod(index: number, period: Period): void {
    const copy = [...this.periodList];
    copy[index] = period;
    this.periodList = copy;
    this.recalculateAndSave();
  }

  onDeletePeriod(index: number): void {
    this.periodList = [
      ...this.periodList.slice(0, index),
      ...this.periodList.slice(index + 1),
    ];
    this.recalculateAndSave();
  }

  private recalculateAndSave(): void {
    const totalDays = totalDaysFromPeriodList(this.periodList);
    this.totalDaysChange.emit(totalDays);

    const validPeriods = this.periodList.filter(
      (period) => period.startDate !== null && period.endDate !== null,
    );

    localStorage.setItem('periodList', JSON.stringify(validPeriods));
  }
}

<button class="btn" (click)="addPeriod()">Add Period</button>

<div class="flex flex-wrap justify-center w-full gap-4">
  <app-period-calculator
    *ngFor="let period of periodList; let i = index"
    [periodInfo]="period"
    (updatePeriod)="onUpdatePeriod(i, $event)"
    (deletePeriod)="onDeletePeriod(i)"
  ></app-period-calculator>
</div>
